DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files_loft"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files_loft/files.txt"

RESULTS_DIR: "./results/case1_loft"
TRAIN_FILE_LIST: "./results/case1_loft/train.txt"
VAL_FILE_LIST: "./results/case1_loft/val.txt"
TEST_FILE_LIST: "./results/case1_loft/est.txt"

MODEL_DIR: "./results/case1_loft/model"
MODEL_NAME: "I2I"

SPACING: 0.035
DIMS: 192
NUM_CONTOUR_POINTS: 30
PATH_START: 2
LOFT: true
LOCAL_MAX_NORM: true
ROTATE: true
RANDOM_CROP: true
PATH_PERTURB: 5

VAL_PATTERNS:
  - OSMSC0110
  - OSMSC0140
  - OSMSC0170
  - cabg5
  - OSMSC0082
  - OSMSC0177

TEST_PATTERNS:
  - OSMSC0006
  - OSMSC0080
  - OSMSC0083
  - OSMSC0101
  - OSMSC0110
  - OSMSC0171
  - OSMSC0178
  - OSMSC0004
  - OSMSC0119
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - OSMSC0179
  - cabg11

TRAIN_PATTERNS:
  - normal1
  - normal4
  - OSMSC0001
  - OSMSC0002
  - OSMSC0003
  - OSMSC0005
  - OSMSC0066
  - OSMSC0068
  - OSMSC0069
  - OSMSC0071
  - OSMSC0072
  - OSMSC0073
  - OSMSC0074
  - OSMSC0078
  - OSMSC0079
  - OSMSC0085
  - OSMSC0087
  - OSMSC0090
  - OSMSC0092
  - OSMSC0093
  - OSMSC0094
  - OSMSC0095
  - OSMSC0096
  - OSMSC0097
  - OSMSC0098
  - OSMSC0099
  - OSMSC0100
  - OSMSC0103
  - OSMSC0104
  - OSMSC0105
  - OSMSC0106
  - OSMSC0108
  - OSMSC0109
  - OSMSC0113
  - OSMSC0115
  - OSMSC0116
  - OSMSC0117
  - OSMSC0118
  - OSMSC0119
  - OSMSC0121
  - OSMSC0125
  - OSMSC0126
  - OSMSC0129
  - OSMSC0130
  - OSMSC0131
  - OSMSC0134
  - OSMSC0135
  - OSMSC0136
  - OSMSC0138
  - OSMSC0139
  - OSMSC0141
  - OSMSC0142
  - OSMSC0143
  - OSMSC0145
  - OSMSC0146
  - OSMSC0147
  - OSMSC0149
  - OSMSC0150
  - OSMSC0151
  - OSMSC0156
  - OSMSC0157
  - OSMSC0158
  - OSMSC0159
  - OSMSC0160
  - OSMSC0161
  - OSMSC0162
  - OSMSC0163
  - OSMSC0166
  - OSMSC0167
  - OSMSC0168
  - OSMSC0169
  - OSMSC0172
  - OSMSC0173
  - OSMSC0174
  - OSMSC0175
  - OSMSC0176
  - OSMSC0178
  - OSMSC0180
  - OSMSC0181
  - OSMSC0182
  - OSMSC0183
  - OSMSC0184
  - OSMSC0185
  - OSMSC0186
  - OSMSC0187
  - OSMSC0189
